logic for PicksController and LikedMovieController
FlickPick/fe_flick_pick pull request #15
Opened 2023-11-05 06:22 UTC by JoopStark

## Description
Set-up flash alerts
Set-up logic for swiping.

## Type of Change

- [ ] **fix**
- [ ] **feat**
- [ ] **test**
- [ ] **refactor**
- [ ] **docs**

## Checklist

- [ ] **Code has been self reviewed**
- [ ] **Code runs without any errors**
- [ ] **Thorough testing has been implemented if adding feature**
- [ ] **All tests pass**

2023-11-05 17:41 UTC, reedhillmar requested changes
I think we all need to sit down as a group and go over this logic before we commit any of this. We really don't have a firm grip of how this part of the app is going to work to commit this logic

2023-11-05 17:41 UTC, reedhillmar commented on app/controllers/application_controller.rb
> +  def require_current_user
I think we might need to check the logic here. The way I'm reading it the flash will send in both cases, but I could be wrong

2023-11-05 17:41 UTC, reedhillmar commented on app/controllers/liked_movies_controller.rb
We need to go over all of this. I don't think we have a firm enough plan of how this step is going to work to have logic written

2023-11-06 22:57 UTC, JoopStark commented on app/controllers/liked_movies_controller.rb
Added liked_movies#create
added selections#waiting_room, #index

2023-11-06 23:06 UTC, ttakahashi1591 commented on app/controllers/liked_movies_controller.rb
> +  # end
This looks like a good set up for the next step!

2023-11-06 23:08 UTC, ttakahashi1591 commented on config/puma.rb
> +port ENV.fetch("PORT") { 5001 }
I think this should be set to 5000?

2023-11-06 23:17 UTC, reedhillmar approved these changes
Some areas for potential refactor, but overall looks good. That was a BIG pr...

2023-11-06 23:17 UTC, reedhillmar commented on app/controllers/application_controller.rb
> +  def require_current_user
That looks like what I would expect

2023-11-06 23:17 UTC, reedhillmar commented on app/controllers/liked_movies_controller.rb
Is there a way to refactor these redirects so we're not passing the queries directly? Not sure, but it would be a bit cleaner/easier to follow

2023-11-06 23:17 UTC, reedhillmar commented on app/controllers/temp_users_controller.rb
> +      redirect_to "/temp_users/#{temp_user_id}/selections/waiting_room?party_id=#{party_id}&access_code=#{params[:access_code]}"
Same as before, can this be refactored?

2023-11-06 23:17 UTC, reedhillmar commented on app/views/layouts/application.html.erb
what happened to all the flashes?

2023-11-06 23:17 UTC, reedhillmar commented on config/puma.rb
> +port ENV.fetch("PORT") { 5001 }
Yes, this should be 5000

2023-11-06 23:17 UTC, merged